# Generated by Django 2.2 on 2021-05-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fullDescription',
            new_name='full_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shortDescription',
            new_name='short_description',
        ),
    ]
