# Generated by Django 2.2 on 2021-05-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
